<?php

namespace App\Http\Controllers;

use App\Models\Friend;
use App\Models\User;
use App\Models\Userpost;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller {
    /**
     * Display a listing of the resource.
     */
    public function view_page($id) {

        // getting all the user data from users table
        $user = User::where("remember_token", "=", $id)->first();

        // getting suggested people data
        $myid = session()->get('user_id');
        $mydata = User::find($myid);

        $suggested_people = User::leftJoin('friends', function ($join) use ($myid) {
            $join->on('users.student_id', '=', 'friends.student_id')->where('friends.friend_id', '=', $myid)->orWhere('users.student_id', '=', 'friends.friend_id');
        })->whereNull('friends.student_id')->whereNull('friends.friend_id')->where('users.student_id', '!=', $myid)->where("graduation_year", "=", $mydata->graduation_year)->select('users.*')->limit(4)->get();
        
        // getting all the images posted by the user from the user_posts table and also filtering the non image posts
        $postedImages = Userpost::select('attachment')->where('posted_by', '=', $user->student_id)->where('attachment', '!=', null)->get()->toArray();

        // getting all the posts of the user to display it in the profile page

        $posts = Userpost::with('getUser')->with("getLikedUser")->where('posted_by', '=', $user->student_id)->where('post_type', '!=', 'job')->orderBy('created_at', 'desc')->get()->toArray();

        $jobs = Userpost::with('getUser')->with("getLikedUser")->where('posted_by', '=', $user->student_id)->where('post_type', '=', 'job')->orderBy('created_at', 'desc')->get()->toArray();

        $friendStatus = Friend::where('student_id', '=', session()->get('user_id'))->where('friend_id', '=', $user['student_id'])->get()->toArray();

        // generating an array for the images only
        $imgArr = [];

        foreach ($postedImages as $img) {

            // if multi post found then the below if-else block will run and prepare the array
            if(strpos($img['attachment'], "||") != false){
                foreach (explode("||", $img['attachment']) as $item) {
                    array_push($imgArr, $item);
                }
            }
            else{   
                array_push($imgArr, $img['attachment']);
            }
        }

        $data = compact("user", "imgArr", "posts", "suggested_people", "jobs", "friendStatus");
        return view('profiles')->with($data);
    }

    public function view_search(Request $request) {
        $search = $request->search;

        $myid = session()->get('user_id');
        $mydata = User::find($myid);

        // TODO: fix search functionality bug
        $searchedData = User::where("name", "LIKE", "%$search%")->orWhere('student_id', "LIKE", "%$search%")->where('student_id', "!=", $myid)->get()->toArray();
        $suggested_people = User::leftJoin('friends', function ($join) use ($myid) {
            $join->on('users.student_id', '=', 'friends.student_id')->where('friends.friend_id', '=', $myid)->orWhere('users.student_id', '=', 'friends.friend_id');
        })->whereNull('friends.student_id')->whereNull('friends.friend_id')->where('users.student_id', '!=', $myid)->where("graduation_year", "=", $mydata->graduation_year)->select('users.*')->limit(4)->get();

        $data = compact("searchedData", "suggested_people");
        return view("searchedprofile")->with($data);
    }

    public function view_edit() {
        $user = User::where("student_id", '=', session()->get('user_id'))->first();
        return view('profile_edit')->with(compact('user'));
    }

    public function save_changes(Request $request) {
        // creating an array to update
        $updateArr = $request->all();

        // fetching the pre existing user's data
        // EXPLANATION: if user has uploaded certificates previously then it should be apended otherwise the files will be replaced!
        $user = User::find(session()->get('user_id'))->toArray();

        // Check if the key exists in the array before removing it and remove it if it is existing
        if (array_key_exists('_token', $updateArr)) {
            // Removing the _token from the associative array as it is not necessary in case of updating
            unset($updateArr['_token']);
        }
        if (array_key_exists('cover_picture', $updateArr)) {
            // Removing the cover_picture from the associative array as it's name will be generated by the system and only the name will be stored!
            unset($updateArr['cover_picture']);
        }
        if (array_key_exists('profile_picture', $updateArr)) {
            // Removing the profile_picture from the associative array as it's name will be generated by the system and only the name will be stored!
            unset($updateArr['profile_picture']);
        }
        if (array_key_exists('verification_document', $updateArr)) {
            // Removing the verification_document from the associative array as it's name will be generated by the system and only the name will be stored!
            unset($updateArr['verification_document']);
        }
        if (array_key_exists('resume', $updateArr)) {
            // Removing the resume from the associative array as it's name will be generated by the system and only the name will be stored!
            unset($updateArr['resume']);
        }
        if (array_key_exists('certificates', $updateArr)) {
            // Removing the certificates from the associative array as it's name will be generated by the system and only the name will be stored!
            unset($updateArr['certificates']);
        }

        // cover photo update handling
        $file = $request->file('cover_picture');
        if (isset($file)) {
            $filename = session()->get('user_id') . "/profile/cover" . '.' . $request->file('cover_picture')->getClientOriginalExtension();
            $request->file('cover_picture')->storeAs('/', $filename, 'public');
            $updateArr['cover_picture'] = $filename;
        }

        // profile photo update handling
        $file = $request->file('profile_picture');
        if (isset($file)) {
            $filename = session()->get('user_id') . "/profile/avatar" . '.' . $request->file('profile_picture')->getClientOriginalExtension();
            $request->file('profile_picture')->storeAs('/', $filename, 'public');
            $updateArr['profile_picture'] = $filename;
            session()->put('user_profile_img', $filename);
        }

        if(array_key_exists('name', $updateArr)){
            session()->put('user_name', $updateArr['name']);
        }

        // verification document update handling
        $file = $request->file('verification_document');
        if (isset($file)) {

            // generating filename
            $filename = session()->get('user_id') . "/verification_document/verify_doc" . '.' . $request->file('verification_document')->getClientOriginalExtension();
            $request->file('verification_document')->storeAs('/', $filename, 'public');
            $updateArr['verification_document'] = $filename;
        }

        // resume update handling
        $file = $request->file('resume');
        if (isset($file)) {

            // generating filename
            $filename = session()->get('user_id') . "/resume/resume" . '.' . $request->file('resume')->getClientOriginalExtension();
            $request->file('resume')->storeAs('/', $filename, 'public');
            $updateArr['resume'] = $filename;
        }


        // certificates update handling [multiple file input supported]
        $file = $request->file('certificates');
        if (isset($file)) {
            $file_arr = [];
            foreach ($request->file('certificates') as $index => $file) {

                // generating array for filename
                $file_to_store = session()->get('user_id') . "/certificates/" . time() . '_' . $index . '.' . $file->getClientOriginalExtension();
                array_push($file_arr, $file_to_store);

                // uploading individual certificates
                $file->storeAs('/', $file_to_store, 'public');
            }

            // generating filename
            $filename = implode("||", $file_arr);

            // if user has already uploaded any certificates then the new files should be appended at the end
            // FORMAT: prefile.ext + || + newfiles.....
            if ($user['certificates']) {
                $filename = $user['certificates'] . "||" . $filename;
            }
            $updateArr['certificates'] = $filename;
        }

        // this code below automatically updates the user data according to the form that is submitted
        $result = User::find(session()->get('user_id'))->update($updateArr);

        // preparating json response
        // TODO: uncomment this lines
        if ($result) {
            return response()->json(['success' => true, 'message' => 'Profile Updated Successfully'], 200);
        }
        else {
            return response()->json(['success' => false, 'message' => 'Failed to update profile'], 422);
        }

        // return redirect(route('profile.edit'));
    }

    public function toggleVisibility(Request $request)
    {
        $studentId =  session()->get('user_id');
        $visibility = $request->input('profile_visibility');


        $user = User::where('student_id', $studentId)->first();

        if ($user) {
            $user->profile_visibility = $visibility;
            $user->save();
            return response()->json(['success' => true,'message' => 'Privacy Update']);//thi sis shobhan
        } else {
            return response()->json(['success' => false, 'message' => 'User not found'], 404);//this is altab
        }
    }

    public function changePassword(Request $request){
        // TODO: implement change password system

        $request->validate([
            'c_old_password' => 'required',
            'c_new_password' => 'required|string|min:6|different:c_old_password',
            'c_new_cpassword_again' => 'required|same:c_new_password',
        ], [
            'c_old_password.required' => 'Please enter your current password.',
            'c_new_password.required' => 'Please enter a new password.',
            'c_new_password.min' => 'The new password must be at least :min characters long.',
            'c_new_password.different' => 'The new password must be different from the current password.',
            'c_new_cpassword_again.required' => 'Please confirm your new password.',
            'c_new_cpassword_again.same' => 'The new passwords do not match.',
        ]);


     // Retrieve the user's email from the session
     $userEmail = session()->get('loggedInUser');

     // Retrieve the user based on the email stored in the session
     $user = User::where('email', $userEmail)->first();

        // Check if the user exists
        if (!$user) {
            return response()->json(['message' => 'User not found.'], 404);
        }

        // Check if the provided current password matches the user's password
        if (!Hash::check($request->c_old_password, $user->password)) {
            return response()->json(['message' => 'The current password is incorrect.'], 422);
        }

        // Update the user's password
        $user->password = Hash::make($request->c_new_password);
        $user->save();

        return response()->json(['message' => 'Password changed successfully.']);
    }
}
